// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCYPr0e8PqwWU98uBaIpNluU2B6TIuzwDc',
    appId: '1:1097165020508:web:b9330cc1309824fee5f599',
    messagingSenderId: '1097165020508',
    projectId: 'wastepoint-5a488',
    authDomain: 'wastepoint-5a488.firebaseapp.com',
    storageBucket: 'wastepoint-5a488.firebasestorage.app',
    measurementId: 'G-VNB2VYVDRJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAveCHn9jS2lkBb_GoGWnPAIatmbSYNAtA',
    appId: '1:1097165020508:android:e0e9bac8ca70003ce5f599',
    messagingSenderId: '1097165020508',
    projectId: 'wastepoint-5a488',
    storageBucket: 'wastepoint-5a488.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhDNkcUKoQVVOhQ0BkxX8kQNMs0bu3aGw',
    appId: '1:1097165020508:ios:7f6fae4fd04bd926e5f599',
    messagingSenderId: '1097165020508',
    projectId: 'wastepoint-5a488',
    storageBucket: 'wastepoint-5a488.firebasestorage.app',
    iosBundleId: 'com.example.mobileAppProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDhDNkcUKoQVVOhQ0BkxX8kQNMs0bu3aGw',
    appId: '1:1097165020508:ios:7f6fae4fd04bd926e5f599',
    messagingSenderId: '1097165020508',
    projectId: 'wastepoint-5a488',
    storageBucket: 'wastepoint-5a488.firebasestorage.app',
    iosBundleId: 'com.example.mobileAppProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCYPr0e8PqwWU98uBaIpNluU2B6TIuzwDc',
    appId: '1:1097165020508:web:469e09a4d92153fae5f599',
    messagingSenderId: '1097165020508',
    projectId: 'wastepoint-5a488',
    authDomain: 'wastepoint-5a488.firebaseapp.com',
    storageBucket: 'wastepoint-5a488.firebasestorage.app',
    measurementId: 'G-V6ENLRXEHM',
  );

}